export const ENTER_MOBILE_MODE = 'ENTER_MOBILE_MODE';
export const EXIT_MOBILE_MODE = 'EXIT_MOBILE_MODE';
export const ENTER_TOUCH_MODE = 'ENTER_TOUCH_MODE';
export const EXIT_TOUCH_MODE = 'EXIT_TOUCH_MODE';
export const SET_APP_WIDTH = 'SET_APP_WIDTH';
export const SET_ONLINE = 'SET_ONLINE';
export const SET_OFFLINE = 'SET_OFFLINE';

export const SET_LOCATIONS = 'SET_LOCATIONS';
export const SET_TRAFFIC_IMAGES = 'SET_TRAFFIC_IMAGES';
