export const ENTER_MOBILE_MODE = 'ENTER_MOBILE_MODE';
export const EXIT_MOBILE_MODE = 'EXIT_MOBILE_MODE';
export const ENTER_TOUCH_MODE = 'ENTER_TOUCH_MODE';
export const EXIT_TOUCH_MODE = 'EXIT_TOUCH_MODE';
export const SET_APP_WIDTH = 'SET_APP_WIDTH';
export const SET_ONLINE = 'SET_ONLINE';
export const SET_OFFLINE = 'SET_OFFLINE';
export const SET_BODY_NO_SCROLL = 'SET_BODY_NO_SCROLL';
export const SET_BODY_SCROLL = 'SET_BODY_SCROLL';

export const SET_TWO_HOUR = 'SET_TWO_HOUR';
export const SET_TWENTY_FOUR_HOUR = 'SET_TWENTY_FOUR_HOUR';
export const SET_FOUR_DAY = 'SET_FOUR_DAY';
export const SET_SELECTED_DATE = 'SET_SELECTED_DATE';
export const SET_SELECTED_TIME = 'SET_SELECTED_TIME';
export const SET_TRAFFIC_CAMERAS = 'SET_TRAFFIC_CAMERAS';
export const CLEAR_TRAFFIC_CAMERAS = 'CLEAR_TRAFFIC_CAMERAS';
